class VenueCategory < ApplicationRecord
  has_many :venues

  def icon_creater(category)
    case category
    when "Restaurant"
      return "fa-solid fa-fork-knife"
    when "Bar"
      return "fa-solid fa-whiskey-glass-ice"
    when "Coffee Shop"
      return "fa-solid fa-cup-togo"
    when "Pub"
      return "fa-solid fa-beer-mug"
    when "Takeaway"
      return "fa-solid fa-burger-fries"
    when "Bakery"
      return "fa-solid fa-cupcake"
    when "Cafe"
      return "fa-solid fa-mug-saucer"
    when "Museum"
      return "fa-solid fa-building-columns"
    when "Cinema"
      return "fa-solid fa-camera-movie"
    when "Night Club"
      return "fa-solid fa-martini-glass"
    when "Theme Park"
      return "fa-solid fa-roller-coaster"
    when "Swimming Pool"
      return "fa-solid fa-person-swimming"
    when "Attraction"
      return "fa-solid fa-ferris-wheel"
    when "Stadium"
      return "fa-solid fa-landmark-flag"
    when "Gym"
      return "fa-solid fa-dumbbell"
    when "Launderette"
      return "fa-solid fa-washing-machine"
    when "Hotel / Hostel"
      return "fa-solid fa-hotel"
    when "Medical Centre"
      return "fa-solid fa-stethoscope"
    when "Parking"
      return "fa-solid fa-square-parking"
    when "Park"
      return "fa-solid fa-trees"
    when "Beach"
      return "fa-solid fa-umbrella-beach"
    when "Allotment"
      return "fa-solid fa-shovel"
    when "Supermarket"
      return "fa-solid fa-cart-shopping"
    when "Beauty & Hygiene Shop"
      return "fa-solid fa-pump-soap"
    when "Convenience Shop"
      return "fa-solid fa-shop"
    when "Post Office"
      return "fa-solid fa-envelope"
    when "Shoe Shop"
      return "fa-solid fa-shoe-prints"
    when "Electronics Shop"
      return "fa-solid fa-laptop"
    when "Mobility Shop"
      return "fa-solid fa-crutches"
    when "Clothing Shop"
      return "fa-solid fa-shirt"
    when "Specialist Food Shop"
      return "fa-solid fa-pot-food"
    when "Pharmacy"
      return "fa-solid fa-prescription-bottle-pill"
    when "Sports Shop"
      return "fa-solid fa-shuttlecock"
    when "Salon"
      return "fa-solid fa-lips"
    when "Hair Dresser"
      return "fa-solid fa-scissors"
    when "Garden Centre"
      return "fa-solid fa-tomato"
    when "Police Station"
      return "fa-solid fa-police-box"
    when "Fire Station"
      return "fa-solid fa-fire-hydrant"
    when "Airport"
      return "fa-solid fa-plane-departure"
    when "Train Station"
      return "fa-solid fa-train"
    when "Underground Station"
      return "fa-solid fa-train-subway-tunnel"
    when "Other"
      return "fa-solid fa-buildings"
    end
  end
end
